# Generated by Django 5.0.4 on 2025-04-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_exit_date', models.DateTimeField()),
                ('entry_exit', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('point_of_passage', models.CharField(max_length=30)),
            ],
        ),
    ]
